### get devices
GET {{host}}/api/v1/devices
Accept: application/json

### get device by id
GET {{host}}/api/v1/devices/shelly25-C46E37
Accept: application/json

### get device by id
PUT {{host}}/api/v1/devices/shelly25-C46E37
Content-Type: application/json

{
"type": "shelly25",
"id": "C46E37",
"displayName": "test",
"properties": [
{
"id": {
"deviceId": {
"id": "C46E37",
"type": "SHELLY_25"
},
"id": "0"
},
"type": "Relay",
"displayName": "Relay",
"isOn": true,
"lastUpdated": "2024-05-03T21:10:01.4Z"
},
{
"id": {
"deviceId": {
"id": "C46E37",
"type": "SHELLY_25"
},
"id": "1"
},
"type": "Relay",
"displayName": "Relay",
"isOn": true,
"lastUpdated": "2024-05-03T21:10:01.451Z"
}
],
"customIdentifiers": {}
}

### switch light
PUT {{host}}/api/v1/devices/shelly25-C46E37/properties/1/values/RelayState
Content-Type: application/json

{
"value": false
}

### add device
POST {{host}}/api/v1/devices
Content-Type: application/json

{
"type": "shelly25",
"id": "AAAAAA",
"displayName": "testDevice"
}

### update device
PUT {{host}}/api/v1/devices/shelly25-AAAAAA
Content-Type: application/json

{
"type": "shelly25",
"id": "AAAAAA",
"displayName": "testDevice2"
}

### delete device by id
DELETE {{host}}/api/v1/devices/shelly25-AAAAAA
Content-Type: application/json

### add device property
POST {{host}}/api/v1/devices/shelly25-AAAAAA/properties
Content-Type: application/json

{
"id": "0",
"type": "Relay",
"displayName": "aaa"
}

### add device property
PUT {{host}}/api/v1/devices/shelly25-AAAAAA/properties/0
Content-Type: application/json

{
"type": "Relay",
"displayName": "bbb"
}

### delete device property
DELETE {{host}}/api/v1/devices/shelly25-AAAAAA/properties/0